"""Small methylation data-asset catalog for Phase B generation.

The catalog is metadata only: it tells the agent which SE-Contracts and contrasts are available.
Generated/local real-data contracts are discovered opportunistically; no real data is committed.
"""
from __future__ import annotations

from dataclasses import dataclass

from .contracts import load_contract


@dataclass(frozen=True)
class MethylationAsset:
    ref: str
    label: str
    group_col: str
    levels: tuple[str, ...]
    profile_id: str
    operations: tuple[str, ...] = ("region_delta_beta", "n_dmps")
    notes: str = ""


_BUNDLED_ASSETS = (
    MethylationAsset(
        ref="se:epicv2_casectrl_demo@1",
        label="EPICv2 synthetic case/control demo",
        group_col="Sample_Group",
        levels=("level1", "level2"),
        profile_id="canonical_epicv2_hg38_v1@1",
        notes="small fixture with a planted region-delta signal",
    ),
    MethylationAsset(
        ref="se:epicv2_casectrl_powered@1",
        label="EPICv2 powered synthetic case/control demo",
        group_col="Sample_Group",
        levels=("level1", "level2"),
        profile_id="canonical_epicv2_hg38_v1@1",
        notes="powered fixture for n-DMP and replication tests",
    ),
)

_LOCAL_REAL_ASSETS = (
    MethylationAsset(
        ref="se:tcga_laml_idh@1",
        label="TCGA-LAML HM450 IDH-mut vs WT",
        group_col="Sample_Group",
        levels=("WT", "IDH_mut"),
        profile_id="canonical_hm450_grch38_v1@1",
        notes="local gitignored real-data contract; generated by ingest tcga-laml",
    ),
    MethylationAsset(
        ref="se:tcga_laml_idh_test@1",
        label="TCGA-LAML HM450 held-out test split",
        group_col="Sample_Group",
        levels=("WT", "IDH_mut"),
        profile_id="canonical_hm450_grch38_v1@1",
        notes="local gitignored held-out split for severity tests",
    ),
)


def methylation_asset_catalog(*, include_missing_local: bool = False) -> tuple[MethylationAsset, ...]:
    """Return known methylation assets.

    Bundled fixtures are always included. Local real-data contracts are included only when
    resolvable unless `include_missing_local=True`, which is useful for help text/documentation.
    """
    out = list(_BUNDLED_ASSETS)
    for asset in _LOCAL_REAL_ASSETS:
        if include_missing_local:
            out.append(asset)
            continue
        try:
            load_contract(asset.ref)
        except FileNotFoundError:
            continue
        out.append(asset)
    return tuple(out)
