"""polymer_grammar — Polymer Claims v1.3 grammar (isolated from formalclaim)."""
from __future__ import annotations

__version__ = "0.1.0"

from .base import _Model
from .leaf import (
    CategoricalLeaf,
    ExistenceLeaf,
    Leaf,
    MeasurementBasis,
    PropositionLeaf,
    QuantityLeaf,
)
from .status import PendingReason, Status
from .strength import AXES, StrengthVector, licensed
from .pattern import Pattern, PatternRef, get_pattern, registry
from .claim import Claim
from .proposition import Direction, NeighborEdge, NeighborEdgeKind, Proposition
from .equivalence import EquivalenceClaim, are_equivalent, equivalence_class
from .licensing import (
    LicenseRoute,
    Licensing,
    MaterializationContext,
    RivalSetClosure,
    Satisfaction,
    SatisfactionVerdict,
)
from .roles import CausalRoles, Role
from .units import DIMENSIONLESS, Dimension, compatible
from .defeat import (
    ATTACK_KINDS,
    DefeatEdge,
    DefeatEdgeKind,
    derived_rebut_edges,
    effective_defeats,
    grounded_extension,
    undermine_edges_from_failed_satisfactions,
)
from .blame import (
    BlameAssignment,
    BlameSet,
    BlameVerdict,
    aggregate_blame,
    duhem_status,
)
from .revision import (
    Entrench,
    RetractionVerdict,
    RevisionResult,
    compare_entrenchment,
    contract,
    corpus_entails,
    entails_closure,
    expand,
    is_consistent,
    restore_consistency,
    revise,
)
from .fdr import (
    FDRLedger,
    FDRTest,
    is_discovery,
    process_stream,
    process_test,
)
from .subject import (
    Cohort,
    CohortDefinition,
    CohortSourceDataset,
    CompositeSubject,
    GeneOrProtein,
    GeneOrProteinIdentifiers,
    GenomicRegion,
    LiteralSubject,
    OntologyTerm,
    PathwayMembers,
    PathwayRef,
    PhenopacketRef,
    PhenopacketRetrieval,
    S4ObjectRef,
    Subject,
    VariantVRS,
)
from .provenance import GenerationMode, Provenance
from .governance import (
    AccessScope,
    Governance,
    HazardClass,
    blocks_reproduction,
    requires_safety_review,
)
from .oracle import (
    ApplicabilityDomain,
    OracleDossier,
    ValidationTier,
    cap_strength,
    decay_tier,
    in_domain,
    referenced_oracle_ids,
    tier_ceiling,
    weakest_tier,
)
from .operations import (
    Comparator,
    ComputeGraph,
    DataHandle,
    EvaluationPlan,
    NodeRef,
    OperationNode,
    OpInput,
    ProducedLeafSpec,
    SatisfactionCriterion,
)
from .evaluate import (
    Adapter,
    Drift,
    EvaluationResult,
    ExecValue,
    IdentityAdapter,
    NodeEvaluation,
    ReferenceAdapter,
    SelfLicensingError,
    VerifiedEvaluation,
    evaluate,
    verify,
)
from .description_length import (
    RevisionDiscovery,
    Schema,
    classify,
    clears_mdl_bar,
    corpus_implied_schema,
    description_length,
    mdl_delta,
    novelty_residual,
    transport,
)
from .representation import (
    META_TIER_ALLOWED_CLOSURES,
    META_TIER_REQUIRED_ROUTE,
    ConstraintTarget,
    OntologyTermTarget,
    PatternTarget,
    RepresentationRevision,
    RevisionOperation,
    RevisionTarget,
    is_representation_revision,
    meets_meta_tier_bar,
)

__all__ = [
    "AXES",
    "Claim",
    "Direction",
    "EquivalenceClaim",
    "_Model",
    "CategoricalLeaf",
    "ExistenceLeaf",
    "Leaf",
    "MeasurementBasis",
    "NeighborEdge",
    "NeighborEdgeKind",
    "Pattern",
    "PatternRef",
    "PendingReason",
    "Proposition",
    "PropositionLeaf",
    "QuantityLeaf",
    "Status",
    "StrengthVector",
    "__version__",
    "are_equivalent",
    "equivalence_class",
    "get_pattern",
    "licensed",
    "LicenseRoute",
    "Licensing",
    "MaterializationContext",
    "registry",
    "RivalSetClosure",
    "Satisfaction",
    "SatisfactionVerdict",
    "CausalRoles",
    "Role",
    "DIMENSIONLESS",
    "Dimension",
    "compatible",
    "ATTACK_KINDS",
    "DefeatEdge",
    "DefeatEdgeKind",
    "derived_rebut_edges",
    "effective_defeats",
    "grounded_extension",
    "undermine_edges_from_failed_satisfactions",
    "BlameAssignment",
    "BlameSet",
    "BlameVerdict",
    "aggregate_blame",
    "duhem_status",
    "Entrench",
    "RetractionVerdict",
    "RevisionResult",
    "compare_entrenchment",
    "contract",
    "corpus_entails",
    "entails_closure",
    "expand",
    "is_consistent",
    "restore_consistency",
    "revise",
    "FDRLedger",
    "FDRTest",
    "is_discovery",
    "process_stream",
    "process_test",
    "Cohort",
    "CohortDefinition",
    "CohortSourceDataset",
    "CompositeSubject",
    "GeneOrProtein",
    "GeneOrProteinIdentifiers",
    "GenomicRegion",
    "LiteralSubject",
    "OntologyTerm",
    "PathwayMembers",
    "PathwayRef",
    "PhenopacketRef",
    "PhenopacketRetrieval",
    "S4ObjectRef",
    "Subject",
    "VariantVRS",
    "GenerationMode",
    "Provenance",
    "AccessScope",
    "Governance",
    "HazardClass",
    "blocks_reproduction",
    "requires_safety_review",
    "ApplicabilityDomain",
    "OracleDossier",
    "ValidationTier",
    "cap_strength",
    "decay_tier",
    "in_domain",
    "referenced_oracle_ids",
    "tier_ceiling",
    "weakest_tier",
    "Comparator",
    "ComputeGraph",
    "DataHandle",
    "EvaluationPlan",
    "NodeRef",
    "OperationNode",
    "OpInput",
    "ProducedLeafSpec",
    "SatisfactionCriterion",
    "Adapter",
    "Drift",
    "EvaluationResult",
    "ExecValue",
    "IdentityAdapter",
    "NodeEvaluation",
    "ReferenceAdapter",
    "SelfLicensingError",
    "VerifiedEvaluation",
    "evaluate",
    "verify",
    "META_TIER_ALLOWED_CLOSURES",
    "META_TIER_REQUIRED_ROUTE",
    "ConstraintTarget",
    "OntologyTermTarget",
    "PatternTarget",
    "RepresentationRevision",
    "RevisionOperation",
    "RevisionTarget",
    "is_representation_revision",
    "meets_meta_tier_bar",
    "Schema",
    "corpus_implied_schema",
    "description_length",
    "transport",
    "mdl_delta",
    "novelty_residual",
    "clears_mdl_bar",
    "classify",
    "RevisionDiscovery",
]
